import { Inter } from "next/font/google";
import "../../styles/global.css"
import DashboardWrapper from "./dashboard";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sunny Mobiles",
  description: "Generated by lumix Solutions",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DashboardWrapper>{children}</DashboardWrapper>
      </body>
    </html>
  );
}